DROP TABLE IF EXISTS usa_accident;
CREATE TABLE usa_accident(
    "index_id"                  INTEGER PRIMARY KEY,
    "ID"                        VARCHAR(15),
    "Source"                    VARCHAR(10),
    "Start_Time"                VARCHAR(45),
    "End_Time"                  VARCHAR(45),
    "Start_Lat"                 double precision,
    "Start_Lng"                 double precision,
    "End_Lat"                   double precision,
    "End_Lng"                   double precision,
    "Distance(mi)"              double precision,
    "Description"               text,
    "Street"                    VARCHAR(100),
    "City"                      VARCHAR(45),
    "County"                    VARCHAR(45),
    "State"                     VARCHAR(45),
    "Zipcode"                   VARCHAR(45),
    "Country"                   VARCHAR(45),
    "Timezone"                  VARCHAR(45),
    "Airport_Code"              VARCHAR(45),
    "Weather_Timestamp"         VARCHAR(45),
    "Temperature(F)"            double precision,
    "Wind_Chill(F)"             double precision,
    "Humidity(%)"               double precision,
    "Pressure(in)"              double precision,
    "Visibility(mi)"            double precision,
    "Wind_Direction"            VARCHAR(45),
    "Wind_Speed(mph)"           double precision,
    "Precipitation(in)"         double precision,
    "Weather_Condition"         VARCHAR(45),
    "Amenity"                     BOOL,
    "Bump"                        BOOL,
    "Crossing"                    BOOL,
    "Give_Way"                    BOOL,
    "Junction"                    BOOL,
    "No_Exit"                     BOOL,
    "Railway"                     BOOL,
    "Roundabout"                  BOOL,
    "Station"                     BOOL,
    "Stop"                        BOOL,
    "Traffic_Calming"             BOOL,
    "Traffic_Signal"              BOOL,
    "Turning_Loop"                BOOL,
    "Sunrise_Sunset"            VARCHAR(10),
    "Civil_Twilight"            VARCHAR(10),
    "Nautical_Twilight"         VARCHAR(10),
    "Astronomical_Twilight"     VARCHAR(10),
    "Severity"                  SMALLINT
);
COPY usa_accident FROM '/tmp/US_Accidents_March23_test.csv' USING DELIMITERS ',';
COPY usa_accident FROM '/tmp/US_Accidents_March23_test_index.csv' USING DELIMITERS ',';
COPY usa_accident_noshf FROM '/tmp/US_Accidents_March23_test_noshf.csv' USING DELIMITERS ',';

